version: '3.8'

services:
  web:
    build: .
    container_name: gepadaria_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    container_name: gepadaria_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sa_padaria_mokele
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: